apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: trading
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels: { app: pg }
  template:
    metadata:
      labels: { app: pg }
    spec:
      containers:
      - name: postgres
        image: postgres:15
        args:
        - "-c"
        - "wal_level=logical"
        - "-c"
        - "max_wal_senders=10"
        - "-c"
        - "max_replication_slots=10"
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef: { name: pg-secret }
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init
        configMap:
          name: pg-init
  volumeClaimTemplates:
  - metadata: { name: data }
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests: { storage: 5Gi }
