---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: trading
  namespace: trading
  annotations:
    strimzi.io/node-pools: "enabled"  
    strimzi.io/kraft: "enabled"  
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # KRaft 
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      num.partitions: 6
      default.replication.factor: 3
      min.insync.replicas: 2
      # KRaft Performance Tunning
      inter.broker.protocol.version: 3.9.0
      log.message.format.version: 3.9.0
  entityOperator:
    topicOperator: {}
    userOperator: {}
    
---
# Combined Controller+Broker Node Pool 
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: trading
  namespace: trading
  labels:
    strimzi.io/cluster: trading
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
  resources:
    requests:
      memory: 6Gi
      cpu: "3"
    limits:
      memory: 6Gi
      cpu: "3"
  jvmOptions:
    -Xms: 3072m
    -Xmx: 3072m